appname = casdoor
httpport = 8000
runmode = dev

driverName = postgres
dataSourceName = user=postgres password=password host=db port=5432 dbname=casdoor sslmode=disable

dbName = casdoor

origin = https://localhost
originFrontend = https://localhost

enableHttps = true
httpsPort = 10443
httpsCertFile = /certs/cert.pem
httpsKeyFile = /certs/key.pem

defaultApplication = app-built-inІ