spring.application.name=backend
server.port=9000

# =========================
# CASDOOR (????? NGINX HTTPS)
# =========================
casdoor.endpoint=https://localhost:10443
casdoor.client-id=bb9ce8c0a83b53d16285
casdoor.client-secret=cbc51354e8fdee0ca049f0dc3805240ee1a6a1d4
casdoor.redirect-uri=https://localhost:9000/callback

# =========================
# SSL BACKEND (???? Spring)
# =========================
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=1